{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78f5da88-1e6f-458d-b0bc-a66f98366c59",
   "metadata": {},
   "outputs": [],
   "source": [
    "#12th Feb Assignment Exception handling-1\n",
    "\"\"\"Q1. What is an Exception in python? Write the difference between Exceptions and syntax errors\"\"\"\n",
    "Ans: An Exception in Python is an error that occurs during the execution of a program. Exceptions are errors that occur \n",
    "at runtime, while syntax errors occur when the code is syntactically incorrect and cannot be parsed by the interpreter. \n",
    "Exceptions are usually caused by user input or system errors, while syntax errors are caused by incorrect code.\n",
    "\n",
    "Exceptions are handled by the program, while syntax errors cannot be handled and must be fixed by the programmer. \n",
    "Exceptions can be caught and handled, while syntax errors cannot. Exceptions can also provide additional information \n",
    "about the error, while syntax errors do not.\n",
    "\n",
    "\"\"\"Q2. What happens when an exception is not handled? Explain with an example\"\"\"\n",
    "Ans: When an exception is not handled in Python, the program will crash and an error message will be displayed. \n",
    "For example, if you try to divide a number by zero, the program will crash and display a ZeroDivisionError:\n",
    "\n",
    "Example:\n",
    "\n",
    "x = 5\n",
    "y = 0\n",
    "\n",
    "z = x / y\n",
    "\n",
    "# Output: ZeroDivisionError: division by zero\n",
    "\n",
    "\"\"\"Q3. Which Python statements are used to catch and handle exceptions? Explain with an example\"\"\"\n",
    "Ans: The Python statements used to catch and handle exceptions are try, except, and finally. \n",
    "Example: \n",
    "try: \n",
    "    # code that may throw an exception \n",
    "except ExceptionType as e: \n",
    "    # code to handle the exception \n",
    "finally: \n",
    "    # code that will always be executed, regardless of whether an exception was thrown or not\n",
    "    \n",
    "In this example, the code in the try block is executed. If an exception is thrown, the code in the except block is executed. Finally, regardless of whether an exception was thrown or not, the code in the finally block is executed.\n",
    "\n",
    "For example, if we have a function that divides two numbers, we can use try and except to catch any ZeroDivisionError exceptions that may be thrown: \n",
    "\n",
    "def divide(x, y): \n",
    "    try: \n",
    "        result = x / y \n",
    "    except ZeroDivisionError: \n",
    "        print(\"Division by zero is not allowed!\") \n",
    "    else: \n",
    "        print(\"Result is\", result) \n",
    "    finally: \n",
    "        print(\"Executing finally clause\") \n",
    "        \n",
    "divide(2, 0) \n",
    "\n",
    "This code will print out \"Division by zero is not allowed!\" and \"Executing finally clause\".\n",
    "\n",
    "\"\"\"Q4. Explain with an example:\"\"\"\n",
    "Ans: \n",
    "A) try and else : try and else are two keywords used in Python to handle exceptions. The try block is used to test a \n",
    "block of code for errors. If an error occurs, the except block is executed.\n",
    "\n",
    "Example:\n",
    "\n",
    "try: \n",
    "    print(x) \n",
    "except: \n",
    "    print(\"An exception occurred\") \n",
    "\n",
    "In this example, the try block checks if the variable x is defined. If it is not defined, an exception will be raised \n",
    "and the except block will be executed.\n",
    "\n",
    "Output:\n",
    "An exception occurred\n",
    "\n",
    "B) Finally: Finally is a keyword in Python that is used to define a block of code that will be executed regardless of \n",
    "whether an exception is thrown or not. It is generally used with try/except blocks.\n",
    "\n",
    "Example:\n",
    "\n",
    "try:\n",
    "   f = open(\"test.txt\",encoding = 'utf-8')\n",
    "   # perform file operations\n",
    "finally:\n",
    "   f.close()\n",
    "\n",
    "In the above example, the file is opened and then some operations are performed on it. Finally, the file is closed \n",
    "regardless of whether an exception was thrown or not.\n",
    "\n",
    "C) Raise: Raise is a keyword in Python that is used to raise an exception. It is used to throw an exception when a \n",
    "certain condition occurs.\n",
    "\n",
    "For example, if we want to check if the user has entered a valid age, we can use the raise keyword to throw an \n",
    "exception if the age is less than 18.\n",
    "\n",
    "age = int(input(\"Enter your age: \"))\n",
    "if age < 18:\n",
    "    raise ValueError(\"Age must be greater than 18\")\n",
    "else:\n",
    "    print(\"You are eligible to vote\")\n",
    "    \n",
    "In this example, if the user enters an age less than 18, a ValueError exception is raised.\n",
    "\n",
    "\"\"\"Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an example\"\"\"\n",
    "Ans: Custom Exceptions are user-defined exceptions in Python. They are used to create custom error messages and to \n",
    "handle errors that are specific to an application. Custom Exceptions allow developers to create their own exceptions \n",
    "that can be raised and handled in the same way as built-in exceptions.\n",
    "\n",
    "We need Custom Exceptions because they allow us to create more meaningful error messages and to handle errors that are \n",
    "specific to our application. For example, if we have a web application that requires users to enter their age, we can \n",
    "create a custom exception called “AgeError” that will be raised when a user enters an invalid age. This will allow us \n",
    "to provide a more meaningful error message to the user, such as “Please enter a valid age”.\n",
    "\n",
    "Example:\n",
    "\n",
    "class AgeError(Exception):\n",
    "    def __init__(self, message):\n",
    "        self.message = message\n",
    "\n",
    "def check_age(age):\n",
    "    if age < 18:\n",
    "        raise AgeError(\"You must be at least 18 years old to use this service\")\n",
    "\n",
    "try:\n",
    "    check_age(17)\n",
    "except AgeError as e:\n",
    "    print(e.message)\n",
    "\n",
    "Output: You must be at least 18 years old to use this service.\n",
    "\n",
    "\"\"\"Q6. Create a custom exception class. Use this class to handle an exception.\"\"\"\n",
    "Ans: class CustomException(Exception): \n",
    "    def __init__(self, message): \n",
    "        self.message = message \n",
    "  \n",
    "try: \n",
    "    raise CustomException(\"This is a custom exception\") \n",
    "  \n",
    "except CustomException as error: \n",
    "    print(error.message)\n",
    "\n",
    "# Output: This is a custom exception\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
